default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: buckbucket
  username: postgres
  password: postgres

test:
  <<: *default
  database: buckbucket_test

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
